### ISSUE TITLE
After identifying locations: It isn't clear what the "tags" in the sidebar are referring to

### ISSUE THREAD

**Issue by clar-reese** [thinkingmachines/linksight#182] opened 2018-09-04 01:41 UTC
The different colors imply that it functions as a legend, yet I didn't see those colors anywhere, or they were unclear to me

**Comment by piafaustino** [comment] 2018-09-08 14:42
Closing because this will be addressed by design changes described here #185

**Closed by piafaustino** 2018-09-08 14:42 UTC
Labels: user experience
