### ISSUE TITLE
Add technical documentation/user-guide for the API

### ISSUE THREAD

**Issue by ljvmiranda921** [thinkingmachines/linksight#283] opened 2018-10-16 00:24 UTC
Interested on creating a technical documentation/user-guide for our API like [this](https://docs.chainer.org/en/stable/)? So that we won't dump everything in README and just point potential contributors to our documentation.

I can help set one up in [ReadTheDocs](https://readthedocs.org/) using [Sphinx](http://www.sphinx-doc.org/en/master/). 

**Possible changes**
- Just add more docstrings
- `docs/` directory to house .RST files

**Comment by piafaustino** [comment] 2018-10-29 05:51
@ljvmiranda921 @marksteve How would this issue be distinct from #297, which refers to documenting the API client?

**Comment by piafaustino** [comment] 2018-10-29 09:48
Duplicate of #297

**Closed by piafaustino** 2018-10-29 09:48 UTC
Labels: documentation
