### ISSUE TITLE
"Switch to a Desktop Device" appears even when using Desktop

### ISSUE THREAD

**Issue by daniellegayares** [thinkingmachines/linksight#161] opened 2018-08-23 05:46 UTC
![image](https://user-images.githubusercontent.com/33336908/44506840-c56aeb00-a6da-11e8-8004-be3ba975f592.png)

**Comment by daniellegayares** [comment] 2018-08-23 11:30
Google Chrome

**Comment by marksteve** [comment] 2018-08-23 15:01
@piafaustino This was done on purpose. It's hard to pick out if a browser is mobile or not cos there's no standard header defining it. This is usually done by checking the user-agent but you need to maintain an ever changing list of rules to determine if a browser is mobile so this method is a bit fragile. I opted to checking the viewport size instead since it is the actual constraint we're trying to impose (i.e. the interface doesn't look good on small screens) and not being "mobile" per se. Thoughts?

**Comment by piafaustino** [comment] 2018-08-25 02:41
Ok this is fine -- @daniellegayares  was your screen tiny when you were accessing Linksight? I tried resizing my browser manually and never saw this happen

**Comment by daniellegayares** [comment] 2018-08-30 06:38
Yes it happens when browser not on full screen

**Comment by piafaustino** [comment] 2018-09-08 14:45
Unable to reproduce. Closing for now

**Closed by piafaustino** 2018-09-08 14:45 UTC
Labels: bug, invalid, user experience
